export const ADD_USER = 'ADD_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_POST = 'ADD_POST;';
export const GET_POSTS = 'GET_POSTS';
export const GET_USER = 'GET_USER';
export const ADD_VOTE = 'ADD_VOTE';
export const ADD_LIKE = 'ADD_LIKE';
export const ADD_DISLIKE = 'ADD_DISLIKE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_COMMENT = 'GET_COMMENT'; // 
export const GET_COORDS = 'GET_COORDS';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
